--- #YAML:1.0
name:               Array-CompareAndFilter
version:            1.0.0
abstract:           functions to compare and filter arrays.
author:
    - H. Klausing <h.klausing (at) gmx.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
